name: Linting

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    lint-yaml:
        name: Lint YAML
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Lint YAML files
              uses: ibiqlik/action-yamllint@v3
              with:
                  file_or_dir: "."
                  config_data: |
                      extends: default
                      rules:
                        line-length:
                          max: 120
                          allow-non-breakable-words: true
                        truthy:
                          allowed-values: ["true", "false", "on", "off", "yes", "no"]

    lint-markdown:
        name: Lint Markdown
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Lint Markdown files
              uses: DavidAnson/github-lint-action@v1
              with:
                  glob: "**/*.md"
